# Generated by Django 3.2.2 on 2021-06-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emergency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospitalname', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='hadmin',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='myrecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospitalname', models.CharField(max_length=50)),
                ('doctorname', models.CharField(max_length=50)),
                ('hospitallocation', models.CharField(max_length=250)),
                ('diseasename', models.CharField(max_length=50)),
                ('documentname', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='')),
                ('prescription', models.FileField(upload_to='')),
                ('description', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescrip_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('diseasename', models.CharField(max_length=50)),
                ('medicinename', models.FileField(upload_to='')),
                ('meal', models.CharField(max_length=10)),
                ('time', models.TimeField()),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Registeration',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('healthissue', models.CharField(default='no', max_length=30)),
                ('interest', models.CharField(default='no', max_length=30)),
                ('hobby', models.CharField(default='no', max_length=30)),
                ('phone', models.CharField(default='no', max_length=13)),
                ('economic_pref', models.CharField(default='moderate', max_length=30)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
    ]
