# Generated by Django 3.2 on 2021-06-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_prescription_medicinename'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='speciality',
            field=models.CharField(default='Multispeciality', max_length=50),
        ),
    ]
